#!/usr/bin/env python3
"""Publishing engine for the Editorial Factory.

Handles:
1. Parsing approved draft markdown (frontmatter, sections, sources, LinkedIn post).
2. Embedding external URLs into the LinkedIn post:
   - Article URL (e.g. PressFlow / Ghost / external blog with added illustrations).
   - Promo Tool URL (e.g. live tools generated by the Software Factory).
3. Unconditional persistence to `published/YYYY-MM-DD_<slug>.md`.
4. Logging to `context/published_log.md` with all live URLs.
5. Persistence to Supabase (articles, claims, live URLs) when configured.
6. Conditional LinkedIn posting via the `LINKEDIN_AUTO_POST` switch:
   - If LINKEDIN_AUTO_POST=true (and LINKEDIN_ACCESS_TOKEN is set): posts to LinkedIn API and records live URL.
   - If LINKEDIN_AUTO_POST=false (default): produces a formatted copy-paste snippet with all embedded links ready.
7. Optional Ghost / PressFlow publishing when configured.

Usage:
  python3 scripts/publish.py context/drafts/YYYY-MM-DD_<slug>_final.md --article-url "https://site.com/post"
  python3 scripts/publish.py context/drafts/YYYY-MM-DD_<slug>_final.md -a "https://site.com/post" -p "https://factory.com/tools/scanner"
  python3 scripts/publish.py --interactive context/drafts/YYYY-MM-DD_<slug>_final.md
  python3 scripts/publish.py --dry-run context/drafts/YYYY-MM-DD_<slug>_final.md -a "https://site.com/post"
"""

import argparse
import datetime
import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def parse_bool_env(var_name: str, default: bool = False) -> bool:
    val = os.environ.get(var_name, "").strip().lower()
    if not val:
        return default
    return val in ("1", "true", "yes", "on", "enable", "enabled")


def parse_draft(file_path: str):
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Parse YAML frontmatter if present
    frontmatter = {}
    body_content = content
    if content.startswith("---"):
        parts = content.split("---", 2)
        if len(parts) >= 3:
            fm_text = parts[1]
            body_content = parts[2].strip()
            for line in fm_text.strip().splitlines():
                if ":" in line:
                    k, v = line.split(":", 1)
                    frontmatter[k.strip()] = v.strip().strip('"').strip("'")

    # Extract headline/title
    title = frontmatter.get("title")
    if not title:
        title_match = re.search(r"^#\s+(.+)$", body_content, re.MULTILINE)
        title = title_match.group(1).strip() if title_match else os.path.basename(file_path)

    slug = frontmatter.get("slug")
    if not slug:
        base = os.path.basename(file_path).replace("_final.md", "").replace("_draft.md", "").replace(".md", "")
        # Strip leading date if present (YYYY-MM-DD_)
        slug = re.sub(r"^\d{4}-\d{2}-\d{2}_", "", base)

    vertical = frontmatter.get("vertical", "general")
    persona = frontmatter.get("persona", "general")
    date_str = frontmatter.get("date", datetime.date.today().isoformat())
    article_url = frontmatter.get("article_url", "")
    promo_url = frontmatter.get("promo_url", "")
    promo_label = frontmatter.get("promo_label", "")

    # Extract LinkedIn post
    linkedin_post = ""
    linkedin_match = re.search(r"<!--\s*linkedin\s*-->\s*(.+)", body_content, re.DOTALL | re.IGNORECASE)
    if linkedin_match:
        linkedin_post = linkedin_match.group(1).strip()
        # Remove linkedin section from the long-form body
        body_article = body_content[:linkedin_match.start()].strip()
    else:
        body_article = body_content.strip()

    # Extract Sources
    sources = []
    sources_match = re.search(r"## Sources\s*(.+)", body_article, re.DOTALL | re.IGNORECASE)
    if sources_match:
        sources_text = sources_match.group(1).strip()
        for s in re.finditer(r"\[(\d+)\]\s*([^\[\n]+)", sources_text):
            sources.append({"index": int(s.group(1)), "citation": s.group(2).strip()})

    return {
        "title": title,
        "slug": slug,
        "vertical": vertical,
        "persona": persona,
        "date": date_str,
        "article_url": article_url,
        "promo_url": promo_url,
        "promo_label": promo_label,
        "body_md": body_article,
        "linkedin_post": linkedin_post,
        "sources": sources,
        "full_content": content,
    }


def embed_links_into_linkedin_post(
    post_text: str,
    article_url: str = "",
    promo_url: str = "",
    promo_label: str = "",
) -> str:
    """Inject external article URL and tool promo URL into LinkedIn post text."""
    if not post_text:
        return ""

    text = post_text
    article_replaced = False
    promo_replaced = False

    # 1. Replace explicit placeholders if present
    if article_url:
        for placeholder in ("{{ARTICLE_URL}}", "[ARTICLE_URL]", "{ARTICLE_URL}"):
            if placeholder in text:
                text = text.replace(placeholder, article_url)
                article_replaced = True

    if promo_url:
        for placeholder in ("{{PROMO_URL}}", "[PROMO_URL]", "{PROMO_URL}"):
            if placeholder in text:
                text = text.replace(placeholder, promo_url)
                promo_replaced = True

    # 2. Append cleanly if URLs exist but weren't replaced via placeholders
    cta_blocks = []
    if article_url and not article_replaced:
        cta_blocks.append(f"📖 Read the full illustrated breakdown: {article_url}")

    if promo_url and not promo_replaced:
        label = promo_label.strip() if promo_label else "🛠️ Try the tool / live demo:"
        if not label.endswith(":"):
            label += ":"
        cta_blocks.append(f"{label} {promo_url}")

    if cta_blocks:
        text = text.rstrip() + "\n\n" + "\n\n".join(cta_blocks)

    return text


def post_to_linkedin(post_text: str, access_token: str, article_url: str = "") -> dict:
    """Post to LinkedIn UGC API with optional article link preview."""
    # First get user's profile URN
    me_url = "https://api.linkedin.com/v2/userinfo"
    me_req = urllib.request.Request(
        me_url,
        headers={
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(me_req) as resp:
            user_data = json.loads(resp.read().decode("utf-8"))
            author_sub = user_data.get("sub")
            if not author_sub:
                raise ValueError("Could not determine user URN from LinkedIn userinfo")
            author_urn = f"urn:li:person:{author_sub}"
    except Exception as e:
        # Fallback to legacy me endpoint
        legacy_req = urllib.request.Request(
            "https://api.linkedin.com/v2/me",
            headers={
                "Authorization": f"Bearer {access_token}",
                "Content-Type": "application/json",
            },
        )
        try:
            with urllib.request.urlopen(legacy_req) as resp:
                legacy_data = json.loads(resp.read().decode("utf-8"))
                author_urn = f"urn:li:person:{legacy_data.get('id')}"
        except Exception:
            raise RuntimeError(f"LinkedIn authentication failed: {e}")

    # UGC Post payload
    share_content = {
        "shareCommentary": {"text": post_text},
        "shareMediaCategory": "NONE",
    }

    if article_url:
        share_content["shareMediaCategory"] = "ARTICLE"
        share_content["media"] = [
            {
                "status": "READY",
                "originalUrl": article_url,
            }
        ]

    post_payload = {
        "author": author_urn,
        "lifecycleState": "PUBLISHED",
        "specificContent": {
            "com.linkedin.ugc.ShareContent": share_content
        },
        "visibility": {"com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"},
    }

    req = urllib.request.Request(
        "https://api.linkedin.com/v2/ugcPosts",
        data=json.dumps(post_payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json",
            "X-Restli-Protocol-Version": "2.0.0",
        },
        method="POST",
    )

    with urllib.request.urlopen(req) as resp:
        res_data = json.loads(resp.read().decode("utf-8"))
        post_urn = res_data.get("id", "")
        # Construct web URL if possible
        post_url = f"https://www.linkedin.com/feed/update/{post_urn}" if post_urn else "https://www.linkedin.com"
        return {"urn": post_urn, "url": post_url}


def sync_to_supabase(data: dict, live_urls: dict):
    supabase_url = os.environ.get("SUPABASE_URL", "").rstrip("/")
    service_key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "")
    if not supabase_url or not service_key:
        print("  [Supabase] SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY not set. Skipping DB sync.")
        return False

    url = f"{supabase_url}/rest/v1/articles"
    payload = {
        "slug": data["slug"],
        "vertical": data["vertical"],
        "headline": data["title"],
        "body_md": data["body_md"],
        "linkedin_post": data["linkedin_post"],
        "sources": data["sources"],
        "status": "published",
        "live_urls": live_urls,
    }

    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "apikey": service_key,
            "Authorization": f"Bearer {service_key}",
            "Content-Type": "application/json",
            "Prefer": "resolution=merge-duplicates",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"  [Supabase] Successfully upserted article '{data['slug']}' (HTTP {resp.status})")
            return True
    except urllib.error.HTTPError as e:
        err_body = e.read().decode("utf-8", errors="replace")
        print(f"  [Supabase] Warning: Upsert failed (HTTP {e.code}): {err_body}")
        return False
    except Exception as e:
        print(f"  [Supabase] Warning: Could not connect to Supabase: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description="Publish an article and embed external illustrated article & tool promo URLs")
    parser.add_argument("draft_file", help="Path to final draft markdown file")
    parser.add_argument("-a", "--article-url", default=None, help="Final URL where the article (with illustrations) is published (e.g. PressFlow/Ghost/blog)")
    parser.add_argument("-p", "--promo-url", default=None, help="URL for an external tool to promote (e.g. from Software Factory)")
    parser.add_argument("--promo-label", default=None, help="Custom label for the promo tool link (e.g. '🛠️ Try the tool:')")
    parser.add_argument("-i", "--interactive", action="store_true", help="Prompt interactively for article URL and promo tool URL")
    parser.add_argument("--dry-run", action="store_true", help="Parse and show what would be published without side effects")
    parser.add_argument("--auto-post-linkedin", action="store_true", default=None, help="Override LINKEDIN_AUTO_POST to true")
    parser.add_argument("--no-auto-post-linkedin", action="store_true", default=None, help="Override LINKEDIN_AUTO_POST to false")
    args = parser.parse_args()

    if not os.path.exists(args.draft_file):
        print(f"Error: file not found: {args.draft_file}", file=sys.stderr)
        return 1

    data = parse_draft(args.draft_file)
    date_val = data["date"]
    slug_val = data["slug"]
    pub_filename = f"{date_val}_{slug_val}.md"
    pub_path = os.path.join(REPO_ROOT, "published", pub_filename)
    log_path = os.path.join(REPO_ROOT, "context", "published_log.md")

    # Resolve URLs with precedence: CLI flag > Interactive > Frontmatter > Env variable fallback
    article_url = args.article_url or data["article_url"]
    promo_url = args.promo_url or data["promo_url"]
    promo_label = args.promo_label or data["promo_label"] or os.environ.get("DEFAULT_PROMO_LABEL", "🛠️ Try the live tool:")

    # Fallback to default base URL from env if available
    if not article_url:
        base_url = os.environ.get("DEFAULT_ARTICLE_BASE_URL", "").rstrip("/")
        if base_url:
            article_url = f"{base_url}/{slug_val}"

    if not promo_url:
        promo_url = os.environ.get("DEFAULT_PROMO_URL", "").strip()

    # Interactive prompt if requested and fields are empty
    if args.interactive:
        print("\n--- Interactive Link Setup ---")
        prompt_art = input(f"Enter final illustrated article URL [{article_url}]: ").strip()
        if prompt_art:
            article_url = prompt_art
        prompt_prm = input(f"Enter tool promo URL [{promo_url}]: ").strip()
        if prompt_prm:
            promo_url = prompt_prm
        if promo_url:
            prompt_lbl = input(f"Enter promo label [{promo_label}]: ").strip()
            if prompt_lbl:
                promo_label = prompt_lbl
        print("------------------------------\n")

    # Embed URLs into LinkedIn post
    final_linkedin_post = embed_links_into_linkedin_post(
        data["linkedin_post"],
        article_url=article_url,
        promo_url=promo_url,
        promo_label=promo_label,
    )
    data["linkedin_post"] = final_linkedin_post

    # Determine LinkedIn Auto-Post switch
    if args.no_auto_post_linkedin:
        auto_post_linkedin = False
    elif args.auto_post_linkedin:
        auto_post_linkedin = True
    else:
        auto_post_linkedin = parse_bool_env("LINKEDIN_AUTO_POST", default=False)

    linkedin_token = os.environ.get("LINKEDIN_ACCESS_TOKEN", "").strip()

    print("=" * 75)
    print(f"PUBLISHING PIPELINE: {data['title']}")
    print("=" * 75)
    print(f"Vertical:        {data['vertical']}")
    print(f"Slug:            {slug_val}")
    print(f"Target file:     published/{pub_filename}")
    print(f"Article URL:     {article_url or '(None - local reader only)'}")
    print(f"Promo Tool URL:  {promo_url or '(None)'}")
    print(f"LinkedIn Switch: {'[ON] (Enabled)' if auto_post_linkedin else '[OFF] (Manual review mode)'}")

    if args.dry_run:
        print("\n[DRY RUN] Actions that would be performed:")
        print(f" 1. Write long-form markdown to {pub_path}")
        print(f" 2. Append entry to {log_path}")
        print(f" 3. Upsert row to Supabase articles table")
        if auto_post_linkedin:
            if linkedin_token:
                print(" 4. Dispatch LinkedIn post via API with embedded links")
            else:
                print(" 4. LinkedIn auto-post is ON but LINKEDIN_ACCESS_TOKEN is missing (would warn/skip API)")
        else:
            print(" 4. LinkedIn auto-post is OFF -> Display copy-paste snippet with embedded links")
        print("\n--- Formatted LinkedIn Post Preview ---")
        print(data["linkedin_post"] or "(No LinkedIn section found)")
        print("-" * 75 + "\n")
        return 0

    # 1. Unconditional Persistence: write to published/
    os.makedirs(os.path.join(REPO_ROOT, "published"), exist_ok=True)
    with open(pub_path, "w", encoding="utf-8") as f:
        f.write(data["full_content"])
    print(f"✓ Saved article to published/{pub_filename}")

    # 2. LinkedIn posting or copy-paste presentation
    live_urls = {}
    if article_url:
        live_urls["article_url"] = article_url
    if promo_url:
        live_urls["promo_url"] = promo_url

    targets = ["published/"]

    if auto_post_linkedin:
        if linkedin_token and data["linkedin_post"]:
            print("→ Dispatching post to LinkedIn...")
            try:
                res = post_to_linkedin(data["linkedin_post"], linkedin_token, article_url=article_url)
                live_urls["linkedin"] = res.get("url", "")
                targets.append("LinkedIn")
                print(f"✓ Successfully posted to LinkedIn: {res.get('url')}")
            except Exception as e:
                print(f"✗ Failed to auto-post to LinkedIn: {e}", file=sys.stderr)
                print("  Surfacing LinkedIn post for manual copy-paste:")
                print("-" * 50)
                print(data["linkedin_post"])
                print("-" * 50)
        else:
            if not linkedin_token:
                print("! LINKEDIN_AUTO_POST=true but LINKEDIN_ACCESS_TOKEN is not set.")
            print("\n" + "=" * 50)
            print("COPY-PASTE READY LINKEDIN POST (WITH EMBEDDED LINKS):")
            print("=" * 50)
            print(data["linkedin_post"])
            print("=" * 50 + "\n")
    else:
        print("\n" + "=" * 50)
        print("LINKEDIN AUTO-POST IS OFF (Manual Review Mode)")
        print("Copy-paste snippet ready (with embedded links):")
        print("=" * 50)
        print(data["linkedin_post"])
        print("=" * 50 + "\n")

    # 3. Append to published_log.md
    os.makedirs(os.path.join(REPO_ROOT, "context"), exist_ok=True)
    target_str = ", ".join(targets)
    url_items = []
    if article_url:
        url_items.append(f"article: {article_url}")
    if promo_url:
        url_items.append(f"tool: {promo_url}")
    if "linkedin" in live_urls:
        url_items.append(f"linkedin: {live_urls['linkedin']}")
    elif not url_items:
        url_items.append("local/site")

    url_str = " | ".join(url_items)
    log_line = f"| {date_val} | {data['vertical']} | {slug_val} | {data['title']} | {target_str} | {url_str} |\n"

    # Ensure log header exists
    if not os.path.exists(log_path) or os.path.getsize(log_path) == 0:
        with open(log_path, "w", encoding="utf-8") as f:
            f.write("# Published Articles Log\n\n| date | vertical | slug | headline | targets | live URLs |\n|---|---|---|---|---|---|\n")

    with open(log_path, "a", encoding="utf-8") as f:
        f.write(log_line)
    print("✓ Appended row to context/published_log.md")

    # 4. Upsert to Supabase
    sync_to_supabase(data, live_urls)

    print("\n✓ Publishing process completed successfully.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
