-- Migration: vertical -> WordPress site routing (public.vertical_sites)
-- One row per editorial vertical, naming the headless WordPress CMS that vertical publishes to.
-- Idempotent — safe to re-run. Apply in the Supabase SQL editor (same convention as
-- software-factory-core/supabase/*.sql — see 0001_articles_editorial_columns.sql).
--
-- Background: articles are generated by the editorial pipeline, persisted to public.articles
-- (which already carries a `vertical` column, see 0001), and then pushed by hand into a
-- headless WordPress CMS whose content the Astro frontends read. Until now the
-- vertical -> destination mapping existed only in the operator's head, so a mis-mapped push
-- is undetectable (a live example: an article titled "AI Price Volatility: The $250k Upkeep
-- Tax" shipped with the raw vertical id as its H1/og:title/Article.headline).
--
-- Invariant enforced here: WordPress always lives on the `cms.` subdomain of the site's own
-- apex domain. The CHECK constraints make that mechanical rather than conventional, so a bad
-- URL cannot be inserted even by hand.
--
-- Consumers: scripts/check_vertical_sites.py (guard), and the WordPress draft connector
-- (Supabase row -> POST /wp-json/wp/v2/posts, status=draft).
--
-- NOTE: run the "verify" query at the bottom after applying. Expect 26 rows:
--   giniloh.com = 21, wellroost.com = 5.

create table if not exists public.vertical_sites (
  vertical_id  text primary key,
  cms_base_url text not null,                    -- e.g. https://cms.giniloh.com  (no trailing slash)
  site_domain  text not null,                    -- e.g. giniloh.com
  frontend_url text not null,                    -- e.g. https://giniloh.com
  active       boolean not null default true,    -- false = vertical muted, never push to it
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- Constraints are added by ONE guarded statement, not by `drop constraint` / `add constraint`
-- pairs: that shape is eight separate statements to paste correctly, and a slipped selection
-- (an orphaned `add constraint` after a semicolon) fails with
-- `42601: syntax error at or near "add"`. This form is safe to re-run and safe when the table
-- already exists from a partial run.
do $$
declare
  c record;
begin
  for c in
    select * from (values
      ('vertical_sites_cms_host_check',
       'cms_base_url = ''https://cms.'' || site_domain'),
      ('vertical_sites_frontend_url_check',
       'frontend_url = ''https://'' || site_domain'),
      ('vertical_sites_no_trailing_slash_check',
       'right(cms_base_url, 1) <> ''/'' and right(frontend_url, 1) <> ''/'''),
      ('vertical_sites_id_shape_check',
       'vertical_id ~ ''^[a-z0-9_]+$''')
    ) as t(name, expr)
  loop
    if not exists (
      select 1 from pg_constraint
      where conname = c.name and conrelid = 'public.vertical_sites'::regclass
    ) then
      execute format('alter table public.vertical_sites add constraint %I check (%s)', c.name, c.expr);
    end if;
  end loop;
end $$;

alter table public.vertical_sites enable row level security;

-- Reads happen server-side with the service-role key (which bypasses RLS). The CMS base URLs
-- are not secrets, but a writable anon table would let anyone redirect where articles land,
-- so no anon access at all is granted here.

create index if not exists vertical_sites_site_domain_idx on public.vertical_sites (site_domain);

-- Seed. Re-runnable: an existing row's URLs are updated in place, never duplicated.
insert into public.vertical_sites (vertical_id, cms_base_url, site_domain, frontend_url) values
  -- ── wellroost.com — "The Decision Engine for Your Home" (pro_homeowner verticals) ──
  ('home_equity_tco',                     'https://cms.wellroost.com', 'wellroost.com', 'https://wellroost.com'),
  ('home_infrastructure_lifecycle_tco',   'https://cms.wellroost.com', 'wellroost.com', 'https://wellroost.com'),
  ('home_ops_execution',                  'https://cms.wellroost.com', 'wellroost.com', 'https://wellroost.com'),
  ('resilient_home_assets',               'https://cms.wellroost.com', 'wellroost.com', 'https://wellroost.com'),
  ('smart_home_telemetry',                'https://cms.wellroost.com', 'wellroost.com', 'https://wellroost.com'),

  -- ── giniloh.com — "Decision Engine for Expensive Choices" ──
  ('agentic_ai',                          'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('agentic_resilience_failure',          'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('ai_observability_qa',                 'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('career_velocity_equity_engineering',  'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('control_tower_exception_orchestration','https://cms.giniloh.com',  'giniloh.com',   'https://giniloh.com'),
  ('demand_sensing_advanced_sop',         'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('enterprise_ai_finops',                'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('enterprise_ai_governance',            'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('enterprise_build_vs_buy',             'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('enterprise_tech_leadership',          'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('expat_cross_border_relocation',       'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('gpu_hardware',                        'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('last_mile_routing_fleet_carbon',      'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('meio_working_capital_tco',            'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('multi_agent_enterprise_fabric',       'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('nhil_infrastructure_ops',             'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('personal_microeconomics_tinkering_tax','https://cms.giniloh.com',  'giniloh.com',   'https://giniloh.com'),
  ('supplier_risk_reshoring_decision',    'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('supply_chain',                        'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('warehouse_automation_robotics_capex',  'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com'),
  ('workstation_compute_economics',       'https://cms.giniloh.com',   'giniloh.com',   'https://giniloh.com')
on conflict (vertical_id) do update
  set cms_base_url = excluded.cms_base_url,
      site_domain  = excluded.site_domain,
      frontend_url = excluded.frontend_url,
      active       = true,
      updated_at   = now();

-- Verify (run after applying):
--   select site_domain, count(*) from public.vertical_sites group by 1 order by 1;
--   -- expect: giniloh.com 21 | wellroost.com 5
--
--   select count(*) from public.vertical_sites;  -- expect 26
--
-- Coverage is enforced in CI-style by scripts/check_vertical_sites.py, which fails if any
-- vertical in context/verticals.json has no row here (and vice versa).
